<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Goto settings'
            on_press: root.manager.current = 'settings'
        Button:
            text: 'Quit'

<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'My settings button'
        Button:
            text: 'Go to New item'
            on_press: root.manager.current = 'newitem'
<NewItem>:
    BoxLayout:
        Button:
            text: 'new button'
        Button:
            text: 'Back to menu'
            on_press: root.manager.current = 'settings'

<Manager>:
    id: screen_manager
    screen_one: screen_one
    screen_two: screen_two
    screen_three: screen_three
    MenuScreen:
        id: screen_one
        name: 'menu'
        manager: screen_manager
    SettingsScreen:
        id: screen_two
        name: 'settings'
        manager: screen_manager

    NewItem:
        id: screen_three
        name: 'newitem'
        manager: screen_manager
