<HomeScreen>:
	GridLayout:
		cols: 3
		spacing: 10
		padding: 10
		Button:
			text: "Timelapse"
			on_press: root.manager.current = 'timelapse'
		Button:
			text: "Slide/Pan"
			on_press: root.manager.current = 'motor'
		Button:
			text: "Camera"
			on_press: root.manager.current = 'camera'
		
		Button:
			text: "Configure"
			on_press: root.manager.current = 'config'
		Button:
			text: "Begin"
			on_press: root.manager.current = 'begin'
		Button:
			text: "Exit"
			on_press: root.endProgram()